version: "2"
linters:
  # default linters: https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - gosec
    - bodyclose
    - misspell
    - gocritic
    - dupword
    - durationcheck
    - errchkjson
    - exhaustive
    - goconst

  settings:
    exhaustive:
      default-signifies-exhaustive: true
