-- check if the current system is WSL2
-- generated by gemini
local function is_wsl2()
  local output = vim.fn.systemlist({ 'uname', '-r' })
  return output[1]:find('microsoft') ~= nil
end

-- check if the current system is using light theme
-- see
--   - https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/reg-query
--   - https://stackoverflow.com/questions/53961305/how-to-get-data-from-a-registry-key-value-via-command-line
--   - https://www7390uo.sakura.ne.jp/wordpress/archives/1359
local function is_apps_use_light_theme()
  local output = vim.fn.systemlist(
    'reg.exe query \'HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize\' /v \'AppsUseLightTheme\' | awk \'{print $3}\'')
  local str = output[3]:gsub("%s+", "")
  return str == '0x1'
end

return (function()
  return {
    is_wsl2 = is_wsl2,
    is_apps_use_light_theme = is_apps_use_light_theme,
  }
end)
