linters:
  # default linters: https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - gosec
    - bodyclose
    - misspell
    - gocritic
    - dupword
    - durationcheck
    - errchkjson
    - exhaustive
    - exportloopref
    - goconst

linters-settings:
  exhaustive:
    default-signifies-exhaustive: true
  goconst:
    ignore-tests: true
