[[plugins]]
repo        = 'Shougo/deoplete.nvim'
on_i        = 1
hook_source = 'call hook#source#deoplete#load()'

[[plugins]]
repo        = 'Shougo/neosnippet'
on_i        = 1
depends     = ['neosnippet-snippets']
hook_source = 'call hook#source#neosnippet#load()'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_i = 1

[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

[[plugins]]
repo        = 'fatih/vim-go'
on_ft       = ['go']
hook_source = 'call hook#source#vim_go#load()'

[[plugins]]
repo        = 'zchee/deoplete-go'
build       = 'make'
on_ft       = ['go']
depends     = ['deoplete.nvim']
hook_source = 'call hook#source#deoplete_go#load()'

[[plugins]]
repo             = 'autozimu/LanguageClient-neovim'
rev              = 'next'
on_ft            = ['rust', 'python']
depends          = ['deoplete.nvim', 'neosnippet']
build            = 'sh install.sh'
hook_post_source = 'call hook#post_update#language_client_neovim#load()'
hook_source      = 'call hook#source#language_client_neovim#load()'

# TODO Should use LSP
[[plugins]]
repo             = 'carlitux/deoplete-ternjs'
hook_post_source = '!npm i -g tern'
on_ft            = ['javascript']
hook_source      = 'call hook#source#deoplete_ternjs#load()'

# TODO Want to use LSP
[[plugins]]
repo             = 'Shougo/deoplete-rct'
hook_post_source = '!gem install rcodetools'
on_ft            = ['ruby']

[[plugins]]
repo        = 'kannokanno/previm'
on_ft       = ['markdown']
hook_source = 'call hook#source#previm#load()'
