[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'
on_i = 1
hook_add = 'call plugins#deoplete#hook_source()'

[[plugins]]
repo = 'zchee/deoplete-go'
on_i = 1
build = 'make'

[[plugins]] # Codic
repo = 'koron/codic-vim'
on_cmd = 'Codic'

[[plugins]] # Emmet
repo = 'mattn/emmet-vim'
on_i = 1
hook_source = 'call plugins#emmet_vim#hook_source()'

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = 'javascript'
hook_add = 'call plugins#yajs#hook_add()'

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = 'javascript'
hook_add = 'let g:jsx_ext_required = 0'

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'javascript'

[[plugins]] # ruby
repo = 'vim-ruby/vim-ruby'
on_ft = 'ruby'

[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = 'scala'

[[plugins]] # Toml
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # Markdown
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown','mkd']
hook_add = 'call plugins#vim_markdown#hook_add()'

[[plugins]] # Html5
repo  = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = 'call plugins#neosnippet#hook_source()'
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']

[[plugins]]
# require "npm install -g tern"
repo = 'carlitux/deoplete-ternjs'
build = 'npm install -g tern'
on_ft = 'javascript'
on_i = 1

[[plugins]]
# require "gem install rcodetools"
# *options "gem install fastri"
repo = 'osyo-manga/vim-monster'
on_ft = 'ruby'
on_i = 1
build = 'gem install rcodetools fastri'
hook_add = '''
let g:monster#completion#rcodetools#backend = "async_rct_complete"
let g:deoplete#sources#omni#input_patterns = {
\   "ruby" : '[^. *\t]\.\w*\|\h\w*::',
\}
'''

[[plugins]]
repo = 'neovimhaskell/haskell-vim'
on_ft = 'haskell'
hook_add = '''
let g:haskell_enable_quantification = 1
let g:haskell_enable_recursivedo = 1
let g:haskell_enable_arrowsyntax = 1
let g:haskell_enable_pattern_synonyms = 1
let g:haskell_enable_typeroles = 1
let g:haskell_enable_static_pointers = 1
'''

[[plugins]]
repo = 'eagletmt/neco-ghc'
on_ft = 'haskell'
build = 'stack install ghc-mod'

[[plugins]]
repo = 'eagletmt/ghcmod-vim'
on_ft = 'haskell'

# Replace haskell operator to unicode characters
# [[plugins]]
# repo = 'enomsg/vim-haskellConcealPlus'
# on_ft = 'haskell'

[[plugins]]
repo = 'ujihisa/ref-hoogle'
on_ft = 'haskell'
build = 'stack install hoogle'

[[plugins]]
repo = 'ujihisa/unite-haskellimport'
on_ft = 'haskell'
build = 'stack install hoogle && hoogle generate && hoogle data'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_source = 'call plugins#vim_go#hook_source()'

[[plugins]]
repo = 'keith/rspec.vim'
on_ft = 'ruby'

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'
hook_add = '''
let g:typescript_indent_disable = 1
'''

[[plugins]]
repo = 'jason0x43/vim-js-indent'
on_ft = ['typescript', 'javascript']
hook_add = '''
let g:js_indent_typescript = 1
let g:js_indent_flat_switch = 1
'''

[[plugins]]
repo = 'mhartington/nvim-typescript'
on_ft = 'typescript'
depends = ['deoplete.nvim']

# [[plugins]]
# repo = 'Quramy/tsuquyomi'
# on_i = 1
# on_ft = 'typescript'
# build = 'npm install -g typescript'
# depends = ['deoplete.nvim']
