[[plugins]]
repo        = 'Shougo/deoplete.nvim'
on_i        = 1
hook_source = 'call hook#source#deoplete#load()'

[[plugins]]
repo        = 'Shougo/neosnippet'
on_i        = 1
depends     = ['neosnippet-snippets']
hook_source = 'call hook#source#neosnippet#load()'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_i = 1

[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

[[plugins]]
repo        = 'fatih/vim-go'
on_ft       = ['go']
hook_source = 'call hook#source#vim_go#load()'

[[plugins]]
repo        = 'zchee/deoplete-go'
build       = 'make'
on_ft       = ['go']
depends     = ['deoplete.nvim']
hook_source = 'call hook#source#deoplete_go#load()'

# TODO Should use LSP
[[plugins]]
repo             = 'carlitux/deoplete-ternjs'
on_ft            = ['javascript']
hook_source      = 'call hook#source#deoplete_ternjs#load()'
hook_post_update = '!npm i -g tern'

# TODO Want to use LSP
[[plugins]]
repo             = 'Shougo/deoplete-rct'
on_ft            = ['ruby']
hook_post_update = '!gem install rcodetools'

[[plugins]]
repo        = 'kannokanno/previm'
on_ft       = ['markdown']
hook_source = 'call hook#source#previm#load()'
