#############################################################
# Lazy on insert
#############################################################
[[plugins]]
repo     = 'Shougo/deoplete.nvim'
if       = 'has("nvim")'
on_i     = 1
hook_add = 'call plugins#deoplete#hook_source()'

[[plugins]] # Emmet
repo        = 'mattn/emmet-vim'
on_i        = 1
hook_source = 'call plugins#emmet_vim#hook_source()'

#############################################################
# Lazy on Command
#############################################################
[[plugins]] # Codic
repo   = 'koron/codic-vim'
on_cmd = 'Codic'

#############################################################
# Lazy on Javascript, Typescipt
#############################################################
[[plugins]]
repo     = 'othree/yajs.vim'
on_ft    = 'javascript'
hook_add = 'call plugins#yajs#hook_add()'

[[plugins]]
repo     = 'mxw/vim-jsx'
on_ft    = 'javascript'
hook_add = 'let g:jsx_ext_required = 0'

[[plugins]]
repo  = 'pangloss/vim-javascript'
on_ft = 'javascript'

[[plugins]]
repo  = 'ternjs/tern_for_vim'
build = 'npm install -g tern'
on_ft = 'javascript'
hook_source = '''
let g:tern#command = ["tern"]
let g:tern#arguments = ["--persistent"]
'''

[[plugins]]
repo  = 'carlitux/deoplete-ternjs'
on_ft = 'javascript'
on_i  = 1

[[plugins]]
repo     = 'leafgarland/typescript-vim'
on_ft    = 'typescript'
hook_add = 'let g:typescript_indent_disable = 1'

[[plugins]]
repo     = 'jason0x43/vim-js-indent'
on_ft    = ['typescript', 'javascript']
hook_add = '''
let g:js_indent_typescript  = 1
let g:js_indent_flat_switch = 1
'''

# [[plugins]]
# repo        = 'Quramy/tsuquyomi'
# on_ft       = 'typescript'
# hook_source = 'let g:tsuquyomi_completion_detail = 1'

[[plugins]]
repo = 'mhartington/nvim-typescript'
on_ft       = 'typescript'
hook_source = '''
let g:nvim_typescript#signature_complete=1
'''

#############################################################
# Lazy on Ruby
#############################################################
[[plugins]] # ruby
repo  = 'vim-ruby/vim-ruby'
on_ft = 'ruby'

[[plugins]]
repo  = 'Shougo/deoplete-rct'
on_ft = 'ruby'

[[plugins]]
repo  = 'keith/rspec.vim'
on_ft = 'ruby'

#############################################################
# Lazy on Haskell
#############################################################
[[plugins]]
repo        = 'neovimhaskell/haskell-vim'
on_ft       = 'haskell'
hook_source = 'call plugins#haskell_vim#hook_source()'

[[plugins]]
repo        = 'eagletmt/neco-ghc'
on_ft       = 'haskell'
build       = 'stack install ghc-mod'
hook_source = 'let g:necoghc_enable_detailed_browse=1'

[[plugins]]
repo  = 'eagletmt/ghcmod-vim'
on_ft = 'haskell'

# Replace haskell operator to unicode characters
# [[plugins]]
# repo = 'enomsg/vim-haskellConcealPlus'
# on_ft = 'haskell'

[[plugins]]
repo  = 'ujihisa/ref-hoogle'
on_ft = 'haskell'
build = 'stack install hoogle'

[[plugins]]
repo  = 'ujihisa/unite-haskellimport'
on_ft = 'haskell'
build = 'stack install hoogle && hoogle generate && hoogle data'

[[plugins]]
repo  = 'itchyny/vim-haskell-indent'
on_ft = 'haskell'

#############################################################
# Lazy on Go
#############################################################
[[plugins]]
repo        = 'fatih/vim-go'
on_ft       = 'go'
hook_source = 'call plugins#vim_go#hook_source()'

[[plugins]]
repo  = 'zchee/deoplete-go'
on_i  = 1
build = 'make'

[[plugins]]
repo  = 'jodosha/vim-godebug'
on_ft = 'go'

#############################################################
# Other
#############################################################
[[plugins]]
repo  = 'derekwyatt/vim-scala'
on_ft = 'scala'

[[plugins]] # Toml
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # Markdown
repo     = 'rcmdnk/vim-markdown'
on_ft    = ['markdown','mkd']
hook_add = 'call plugins#vim_markdown#hook_add()'

[[plugins]] # Html5
repo  = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo        = 'Shougo/neosnippet'
hook_source = 'call plugins#neosnippet#hook_source()'
on_i        = 1
on_ft       = ['snippet']
depends     = ['neosnippet-snippets']

[[plugins]]
repo  = 'rhysd/vim-crystal'
on_ft = 'crystal'

[[plugins]]
repo  = 'chrisbra/csv.vim'
on_ft = 'csv'

[[plugins]]
repo  = 'zchee/deoplete-jedi'
on_ft = 'python'
hook_source = '''
let g:deoplete#sources#jedi#show_docstring = 1
'''

[[plugins]]
repo  = 'ervandew/eclim'
build = '''
ant -Declipse.home="/Applications/Eclipse.app/Contents/Eclipse" -Dvim.files="/Users/ryuta/.config/nvim"
!mv $XDG_CONFIG_HOME/nvim/eclim/plugin $XDG_CONFIG_HOME/nvim/plugin
'''
on_ft = 'java'

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = 'slim'

[[plugins]]
repo        = 'elzr/vim-json'
on_ft       = 'json'
hook_source = 'let g:vim_json_syntax_conceal = 0'
