[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

[[plugins]]
repo = 'cohama/agit.vim'
on_cmd = 'Agit'

[[plugins]]
repo = 'previm/previm'
on_ft = ["markdown"]
hook_source = '''
let g:previm_open_cmd = "open"
'''

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
hook_source = 'call hook#source#vim_go#load()'

[[plugins]]
repo = 'dart-lang/dart-vim-plugin'
on_ft = ["dart"]

[[plugins]]
repo = 'andrewstuart/vim-kubernetes'
on_ft = ['yaml']
