[[plugins]]
repo        = 'Shougo/deoplete.nvim'
on_i        = 1
hook_source = 'call hook#source#deoplete#load()'

[[plugins]]
repo    = 'Shougo/neosnippet'
on_i    = 1
depends = ['neosnippet-snippets']

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_i = 1

[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

[[plugins]]
repo        = 'fatih/vim-go'
on_ft       = ['go']
hook_source = 'call hook#source#vim_go#load()'

[[plugins]]
repo        = 'zchee/deoplete-go'
build       = 'make'
on_ft       = ['go']
depends     = ['deoplete.nvim']
hook_source = 'call hook#source#deoplete_go#load()'
