[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'
on_i = 1
hook_add = 'call plugins#deoplete#hook_add()'
hook_source = 'call plugins#deoplete#hook_source()'

[[plugins]] # Codic
repo = 'koron/codic-vim'
on_cmd = 'Codic'

[[plugins]] # Emmet
repo = 'mattn/emmet-vim'
on_i = 1
hook_source = 'call plugins#emmet_vim#hook_source()'

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = 'javascript'
hook_add = 'call plugins#yajs#hook_add()'

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = 'javascript'
hook_add = 'let g:jsx_ext_required = 0'

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'javascript'

[[plugins]] # ruby
repo = 'vim-ruby/vim-ruby'
on_ft = 'ruby'

[[plugins]] # Toml
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # Markdown
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown','mkd']
hook_add = 'call plugins#vim_markdown#hook_add()'

[[plugins]] # Html5
repo  = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = 'call plugins#neosnippet#hook_source()'
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']

[[plugins]]
# require "npm install -g tern"
repo = 'carlitux/deoplete-ternjs'
build = 'npm install -g tern'
on_ft = 'javascript'
on_i = 1

[[plugins]]
# require "gem install rcodetools"
# *options "gem install fastri"
repo = 'osyo-manga/vim-monster'
on_ft = 'ruby'
on_i = 1
